// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cumsumC
std::vector<double> cumsumC(std::vector<double> x);
RcppExport SEXP bayesDP_cumsumC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    __result = Rcpp::wrap(cumsumC(x));
    return __result;
END_RCPP
}
// equalgreaterouterC
LogicalVector equalgreaterouterC(int a, NumericVector b);
RcppExport SEXP bayesDP_equalgreaterouterC(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    __result = Rcpp::wrap(equalgreaterouterC(a, b));
    return __result;
END_RCPP
}
// ppexp
double ppexp(double q, const vec& x, const vec& cuts);
RcppExport SEXP bayesDP_ppexp(SEXP qSEXP, SEXP xSEXP, SEXP cutsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< const vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const vec& >::type cuts(cutsSEXP);
    __result = Rcpp::wrap(ppexp(q, x, cuts));
    return __result;
END_RCPP
}
// ppexpM
vec ppexpM(double q, const mat& x, const vec& cuts);
RcppExport SEXP bayesDP_ppexpM(SEXP qSEXP, SEXP xSEXP, SEXP cutsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< const mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const vec& >::type cuts(cutsSEXP);
    __result = Rcpp::wrap(ppexpM(q, x, cuts));
    return __result;
END_RCPP
}
// ppexpC
double ppexpC(int q, NumericVector rate, NumericVector t);
RcppExport SEXP bayesDP_ppexpC(SEXP qSEXP, SEXP rateSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    __result = Rcpp::wrap(ppexpC(q, rate, t));
    return __result;
END_RCPP
}
// ppexpCV
NumericVector ppexpCV(int q, NumericMatrix rate, NumericVector t);
RcppExport SEXP bayesDP_ppexpCV(SEXP qSEXP, SEXP rateSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    __result = Rcpp::wrap(ppexpCV(q, rate, t));
    return __result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP bayesDP_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// rowSumsC
NumericVector rowSumsC(NumericMatrix x);
RcppExport SEXP bayesDP_rowSumsC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(rowSumsC(x));
    return __result;
END_RCPP
}
