// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sigma2marginal
SEXP sigma2marginal(int n, const arma::vec& grid, const arma::mat& XtX, const arma::mat& SigmaBetaInv, const arma::mat& Xstar, const arma::vec& Xty, const arma::vec& mu0, const arma::vec& ystar);
RcppExport SEXP bayesDP_sigma2marginal(SEXP nSEXP, SEXP gridSEXP, SEXP XtXSEXP, SEXP SigmaBetaInvSEXP, SEXP XstarSEXP, SEXP XtySEXP, SEXP mu0SEXP, SEXP ystarSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaBetaInv(SigmaBetaInvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xstar(XstarSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xty(XtySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ystar(ystarSEXP);
    __result = Rcpp::wrap(sigma2marginal(n, grid, XtX, SigmaBetaInv, Xstar, Xty, mu0, ystar));
    return __result;
END_RCPP
}
// betaRegSampler
arma::mat betaRegSampler(const arma::vec& sigma2, const arma::mat& XtX, const arma::mat& SigmaBetaInv, const arma::vec& mu0, const arma::vec& Xty, int nsamples);
RcppExport SEXP bayesDP_betaRegSampler(SEXP sigma2SEXP, SEXP XtXSEXP, SEXP SigmaBetaInvSEXP, SEXP mu0SEXP, SEXP XtySEXP, SEXP nsamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigmaBetaInv(SigmaBetaInvSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xty(XtySEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    __result = Rcpp::wrap(betaRegSampler(sigma2, XtX, SigmaBetaInv, mu0, Xty, nsamples));
    return __result;
END_RCPP
}
// ppexpV
double ppexpV(double q, const arma::vec& x, const arma::vec& cuts);
RcppExport SEXP bayesDP_ppexpV(SEXP qSEXP, SEXP xSEXP, SEXP cutsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cuts(cutsSEXP);
    __result = Rcpp::wrap(ppexpV(q, x, cuts));
    return __result;
END_RCPP
}
// ppexpM
arma::vec ppexpM(double q, const arma::mat& x, const arma::vec& cuts);
RcppExport SEXP bayesDP_ppexpM(SEXP qSEXP, SEXP xSEXP, SEXP cutsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cuts(cutsSEXP);
    __result = Rcpp::wrap(ppexpM(q, x, cuts));
    return __result;
END_RCPP
}
