// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ppexp
double ppexp(double q, const arma::vec& x, const arma::vec& cuts);
RcppExport SEXP bayesDP_ppexp(SEXP qSEXP, SEXP xSEXP, SEXP cutsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cuts(cutsSEXP);
    __result = Rcpp::wrap(ppexp(q, x, cuts));
    return __result;
END_RCPP
}
