# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigma2marginal <- function(n, grid, XtX, SigmaBetaInv, Xstar, Xty, mu0, ystar) {
    .Call('_bayesDP_sigma2marginal', PACKAGE = 'bayesDP', n, grid, XtX, SigmaBetaInv, Xstar, Xty, mu0, ystar)
}

sigma2marginalmc <- function(n, grid, XtX, SigmaBetaInv, Xstar, Xty, mu0, ystar) {
    .Call('_bayesDP_sigma2marginalmc', PACKAGE = 'bayesDP', n, grid, XtX, SigmaBetaInv, Xstar, Xty, mu0, ystar)
}

betaRegSampler <- function(sigma2, XtX, SigmaBetaInv, mu0, Xty, nsamples) {
    .Call('_bayesDP_betaRegSampler', PACKAGE = 'bayesDP', sigma2, XtX, SigmaBetaInv, mu0, Xty, nsamples)
}

betaRegSamplermc <- function(sigma2, XtX, SigmaBetaInv, SigmaBetaInvID, mu0, Xty, nsamples) {
    .Call('_bayesDP_betaRegSamplermc', PACKAGE = 'bayesDP', sigma2, XtX, SigmaBetaInv, SigmaBetaInvID, mu0, Xty, nsamples)
}

ppexpV <- function(q, x, cuts) {
    .Call('_bayesDP_ppexpV', PACKAGE = 'bayesDP', q, x, cuts)
}

ppexpM <- function(q, x, cuts) {
    .Call('_bayesDP_ppexpM', PACKAGE = 'bayesDP', q, x, cuts)
}

