# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumsumC <- function(x) {
    .Call('bayesDP_cumsumC', PACKAGE = 'bayesDP', x)
}

equalgreaterouterC <- function(a, b) {
    .Call('bayesDP_equalgreaterouterC', PACKAGE = 'bayesDP', a, b)
}

ppexp <- function(q, x, cuts) {
    .Call('bayesDP_ppexp', PACKAGE = 'bayesDP', q, x, cuts)
}

ppexpM <- function(q, x, cuts) {
    .Call('bayesDP_ppexpM', PACKAGE = 'bayesDP', q, x, cuts)
}

ppexpC <- function(q, rate, t) {
    .Call('bayesDP_ppexpC', PACKAGE = 'bayesDP', q, rate, t)
}

ppexpCV <- function(q, rate, t) {
    .Call('bayesDP_ppexpCV', PACKAGE = 'bayesDP', q, rate, t)
}

rcpp_hello_world <- function() {
    .Call('bayesDP_rcpp_hello_world', PACKAGE = 'bayesDP')
}

rowSumsC <- function(x) {
    .Call('bayesDP_rowSumsC', PACKAGE = 'bayesDP', x)
}

