# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumsum2 <- function(x) {
    .Call('bayesDP_cumsum2', PACKAGE = 'bayesDP', x)
}

equalgreaterouterC <- function(a, b) {
    .Call('bayesDP_equalgreaterouterC', PACKAGE = 'bayesDP', a, b)
}

ppexpC <- function(x) {
    .Call('bayesDP_ppexpC', PACKAGE = 'bayesDP', x)
}

ppexpCV <- function(x) {
    .Call('bayesDP_ppexpCV', PACKAGE = 'bayesDP', x)
}

rcpp_hello_world <- function() {
    .Call('bayesDP_rcpp_hello_world', PACKAGE = 'bayesDP')
}

rowSumsC <- function(x) {
    .Call('bayesDP_rowSumsC', PACKAGE = 'bayesDP', x)
}

